package com.easybeam.domain.enumeration;

/**
 * The SynchronizationStrategy enumeration.
 */
public enum SynchronizationStrategy {
    BLANK,WAIT_FOR_TEXT_PRESENT,WAIT_FOR_TEXT_NOT_PRESENT,WAIT_FOR_OBJECT_DISPLAY,WAIT_FOR_OBJECT_HIDDEN,WAIT_FOR_OBJECT_ENABLE,WAIT_FOR_OBJECT_DISABLE,WAIT_FOR_OBJECT_PROPERTY_CHANGE,IMPLICITLY_WAIT,COMPOSIT_CONDITION
}
