version: '2'
services:
    easybeam-app:
        image: easybeam
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://easybeam-mysql:3306/easybeam?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    easybeam-mysql:
        extends:
            file: mysql.yml
            service: easybeam-mysql
